apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- manifests

patches:
  - path: patches/deployment.yaml
  - target:
      kind: Deployment
      name: frontend-podinfo
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 100m
          memory: 128Mi
