apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gametscharlos@gmail.com
    privateKeySecretRef:
      name: letsencrypt-app
    solvers:
    - http01:
        ingress:
          class: traefik
