apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-whoami
  namespace: whoami
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/whoami`)
    kind: Rule
    services:
      - kind: Service
        name: whoami
        port: 80
